const $=id=>document.getElementById(id);
const themes={
  yt:{name:'YouTube',sub:'紅色的小小收藏',bg:'#fff8f8',surface:'#ffffff',accent:'#e83e51',swatch:['#e83e51','#ffb4bd','#ffffff']},
  twitch:{name:'Twitch',sub:'紫色的直播時光',bg:'#171020',surface:'#231932',accent:'#b294ff',swatch:['#b294ff','#e29fe8','#482a71']},
  trans:{name:'LGBTQ+ · Trans',sub:'粉藍、粉紅與白色',bg:'#fff7fb',surface:'#ffffff',accent:'#de7eaf',swatch:['#69bbd7','#f4b3cc','#ffffff']},
  dark:{name:'Dark mode',sub:'柔柔的深色夜晚',bg:'#11131b',surface:'#1d202b',accent:'#aab6df',swatch:['#1d202b','#aab6df','#b8aadf']},
  light:{name:'Light mode',sub:'乾淨明亮的日常',bg:'#f7f8fc',surface:'#ffffff',accent:'#658ed4',swatch:['#658ed4','#bde5ec','#ffffff']},
  neon:{name:'Neon',sub:'原本的薄荷霓虹',bg:'#0c121b',surface:'#141f2c',accent:'#6ee7d0',swatch:['#6ee7d0','#69b8d5','#203142']},
  'neon-pink':{name:'Neon pink',sub:'有一點夢幻的粉色',bg:'#1b1021',surface:'#2b1931',accent:'#ff8edb',swatch:['#ff8edb','#c09aff','#613a83']}
};
let page='channels',channel=null,kind='video',downloadedOnly=false,offset=0,logJob='',busy=false,channels=[],imageRole='avatar',prefs={theme:'trans',accent:'',background:'',surface:''};
const labels={queued:'等待下載 / 重試',downloading:'下載中',recording:'● 直播錄製中',done:'已下載',failed:'失敗'};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function button(text,fn,cls='ghost'){const n=el('button',text,cls);n.type='button';n.onclick=()=>Promise.resolve(fn()).catch(notice);return n;}
function notice(e){$('notice').textContent=e.message||String(e);}
async function api(path,body){const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error||r.statusText);return j;}
function brightness(hex){const c=hex.slice(1).match(/../g).map(v=>parseInt(v,16));return c[0]*.299+c[1]*.587+c[2]*.114;}
function applyPrefs(){const root=document.documentElement;root.dataset.theme=prefs.theme;for(const [key,css] of [['accent','--accent'],['background','--bg'],['surface','--surface']]){if(prefs[key])root.style.setProperty(css,prefs[key]);else root.style.removeProperty(css)}if(prefs.accent)root.style.setProperty('--accent-text',brightness(prefs.accent)>160?'#26313b':'#ffffff');else root.style.removeProperty('--accent-text');localStorage.setItem('channel-vault-theme',JSON.stringify(prefs));}
function renderSettings(){const list=$('theme-options');list.replaceChildren();for(const [key,t] of Object.entries(themes)){const b=button('',()=>{prefs={...prefs,theme:key,accent:'',background:'',surface:''};applyPrefs();renderSettings()},'theme-option'+(prefs.theme===key?' selected':''));b.setAttribute('aria-pressed',String(prefs.theme===key));const swatch=el('div',undefined,'theme-swatch');swatch.style.background=t.bg;for(const color of t.swatch){const dot=el('span');dot.style.background=color;swatch.append(dot)}b.append(swatch,el('span',t.name),el('small',t.sub));list.append(b)}const t=themes[prefs.theme];$('accent-color').value=prefs.accent||t.accent;$('background-color').value=prefs.background||t.bg;$('surface-color').value=prefs.surface||t.surface;renderRuntimeSettings();renderCookieSettings();$('x-api-status').textContent=prefs.x_api_configured?'Token 已保存':'尚未設定 Token';}
try{const cached=JSON.parse(localStorage.getItem('channel-vault-theme'));if(cached&&themes[cached.theme]){prefs=cached;applyPrefs()}}catch{}
for(const [id,key] of [['accent-color','accent'],['background-color','background'],['surface-color','surface']])$(id).oninput=e=>{prefs[key]=e.target.value;applyPrefs()};
$('save-settings').onclick=async()=>{try{prefs=await api('/api/settings',prefs);applyPrefs();notice('你的配色已儲存 ♡')}catch(e){notice(e)}};
$('reset-colors').onclick=()=>{prefs={...prefs,theme:prefs.theme,accent:'',background:'',surface:''};applyPrefs();renderSettings();notice('已還原主題原色，按儲存後永久套用。')};
function show(p){page=p;offset=0;for(const id of ['channels','single','all','detail','logs','settings'])$(id).hidden=id!==p;document.querySelectorAll('nav button').forEach(n=>n.classList.toggle('selected',n.dataset.page===p));$('paging').hidden=true;if(p==='settings')renderSettings();refresh().catch(notice);}
document.querySelectorAll('nav button').forEach(n=>n.onclick=()=>show(n.dataset.page));
$('home').onclick=()=>show('channels');$('settings-shortcut').onclick=()=>show('settings');$('back').onclick=()=>show('channels');
$('videos-tab').onclick=()=>{kind='video';offset=0;refresh().catch(notice)};
$('live-tab').onclick=()=>{kind='live';offset=0;refresh().catch(notice)};
$('all-filter').onclick=()=>{downloadedOnly=false;offset=0;refresh().catch(notice)};
$('downloaded-filter').onclick=()=>{downloadedOnly=true;offset=0;refresh().catch(notice)};
$('subscribe').onsubmit=async e=>{e.preventDefault();try{await api('/api/channels',{url:$('channel-url').value,name:$('subscription-name').value});$('channel-url').value='';$('subscription-name').value='';notice('已新增訂閱，開始收錄影片並監控直播 ♡');await refresh()}catch(e){notice(e)}};
$('download').onsubmit=async e=>{e.preventDefault();try{const j=await api('/api/download',{url:$('link-url').value,channel_id:$('download-target').value||null});$('link-url').value='';notice(`收藏任務 #${j.id} 已加入佇列`);await refresh()}catch(e){notice(e)}};
$('update').onclick=async()=>{try{await api('/api/update',{});notice('已啟動更新檢查，結果請看 Log。')}catch(e){notice(e)}};
$('apply-log').onclick=()=>{logJob=$('log-job').value;refresh().catch(notice)};
$('prev').onclick=()=>{offset=Math.max(0,offset-100);refresh().catch(notice)};
$('next').onclick=()=>{offset+=100;refresh().catch(notice)};
function date(t){return t?new Date(t*1000).toLocaleDateString():'尚未檢查'}
function image(src,alt,fallback){const img=el('img');img.src=src;img.alt=alt;img.loading='lazy';img.onerror=()=>{img.remove();if(fallback)fallback()};return img;}
function avatar(c){const a=el('div',undefined,'avatar');const fallback=()=>{a.textContent=(c.name||'♡').slice(0,1)};fallback();if(c.avatar){a.textContent='';a.append(image(`/asset/channel/${c.id}/avatar?v=${c.active_avatar||0}`,c.name+' 的頭像',fallback))}return a;}
function banner(c){const b=el('div',undefined,'banner');if(c.banner){b.classList.add('has-image');b.append(image(`/asset/channel/${c.id}/banner?v=${c.active_banner||0}`,c.name+' 的 banner',()=>b.classList.remove('has-image')))}return b;}
function openChannel(c){channel=c.id;kind='video';downloadedOnly=true;renderHero(c);renderSources(c);$('channel-name').value=c.name;show('detail')}
function renderHero(c){const h=el('div',undefined,'channel-hero');h.append(banner(c));const info=el('div',undefined,'hero-info'),text=el('div',undefined,'hero-text');text.append(el('h1',c.name),el('div',`${c.url.split('/').pop()} · ${c.downloaded} 份收藏 · ${c.recording} 場錄製中`,'muted'));if(c.description)text.append(el('p',c.description,'hero-description'));info.append(avatar(c),text,button(c.enabled?'♡ 追蹤中':'恢復追蹤',async()=>{await api(`/api/channels/${c.id}/toggle`,{});channels=await api('/api/channels');renderHero(channels.find(x=>x.id===c.id))}));h.append(info);const controls=el('div',undefined,'hero-controls');const hasYoutube=(c.sources||[]).some(x=>x.platform==='youtube');const ref=button(c.image_status==='processing'?'正在取得圖片…':'↻ 重新取得 YouTube 圖片',async()=>{await api(`/api/channels/${c.id}/images/refresh`,{});notice('已安排取得最新圖片，舊版本會保留。')},'ghost');ref.disabled=!hasYoutube||c.image_status==='processing';controls.append(ref,button('♡ 更換頭像 / Banner',()=>openImages(),'ghost'));text.append(controls);if(c.image_error)text.append(el('div',c.image_error,'error'));$('channel-hero').replaceChildren(h)}
function renderChannels(list){populateTargets(list);const target=$('channel-list');target.replaceChildren();if(!list.length)target.append(el('p','☁ 新增第一個頻道，讓收藏開始吧。','empty'));for(const c of list){const card=el('article',undefined,'channel-card'),b=banner(c);b.setAttribute('role','button');b.tabIndex=0;b.setAttribute('aria-label','開啟 '+c.name);b.onclick=()=>openChannel(c);b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openChannel(c)}};const content=el('div',undefined,'channel-card-content'),top=el('div',undefined,'channel-card-top');top.append(avatar(c),el('span',c.recording?'● 直播錄製中':c.enabled?'♡ 追蹤中':'暫停中','badge '+(c.recording?'recording':'')));content.append(top,button(c.name,()=>openChannel(c),'channel-title'),el('div',c.url.split('/').pop(),'channel-handle'));const stats=el('div',undefined,'channel-stats');const l=el('span'),r=el('span');l.append(el('strong',String(c.downloaded)),el('span','已收藏影音'));r.append(el('strong',date(c.last_scan)),el('span','最近掃描'));stats.append(l,r);content.append(stats);const tags=el('div',undefined,'provider-tags');for(const source of c.sources||[]){tags.append(el('span',providerName(source.platform)+(source.enabled?'':' · 暫停')))}content.append(tags);if(c.error)content.append(el('div',c.error,'error'));const actions=el('div',undefined,'actions');actions.append(button('進入影音庫 →',()=>openChannel(c)),button('重新掃描',async()=>{await api(`/api/channels/${c.id}/scan`,{});notice('已安排重新掃描，頭像與 banner 也會更新。')}),button(c.enabled?'暫停':'恢復',async()=>{await api(`/api/channels/${c.id}/toggle`,{});busy=false;await refresh()}));content.append(actions);card.append(b,content);target.append(card)}}
const roleLabels={video:'↓ 最高畫質原檔',mp3:'♫ MP3',preview:'↓ 播放副本'};
function downloadLinks(files,target){files.filter(f=>roleLabels[f.role||'video']).forEach((f,i)=>{const a=el('a',roleLabels[f.role||'video']+(files.filter(x=>x.role===f.role).length>1?' '+(i+1):''));a.href='/file/'+f.id;target.append(a)})}
function renderJobs(jobs,target){target.replaceChildren();if(!jobs.length)target.append(el('p',downloadedOnly&&page==='detail'?'☁ 這裡還沒有完成的收藏，切換「全部」可看下載進度。':'☁ 目前沒有影音項目。','empty'));for(const j of jobs){const card=el('article',undefined,'video-card');const thumb=button('',()=>play(j),'thumbnail-button');thumb.setAttribute('aria-label','播放 '+j.title);const img=j.files.find(f=>f.role==='thumbnail');if(img||j.thumbnail)thumb.append(image(img?'/stream/'+img.id:j.thumbnail,j.title+' 縮圖',()=>thumb.prepend(el('span','♫','thumb-symbol'))));else thumb.append(el('span',j.kind==='live'?'☁':'♫','thumb-symbol'));thumb.append(el('span',labels[j.status]||j.status,'badge '+j.status));if(j.status==='done')thumb.append(el('span','▶','play-bubble'));card.append(thumb,button(j.title,()=>play(j),'video-title'),el('div',`${date(j.created)} · ${j.height?j.height+'p · ':''}${j.kind==='live'?'直播 / 回放':'影片'} · ${j.source_platform?providerName(j.source_platform)+' · ':''}#${j.id}`,'job-meta'));const links=el('div',undefined,'file-links');downloadLinks(j.files.filter(f=>f.role!=='preview'),links);card.append(links);if(j.status==='done'&&j.derivative_status!=='ready')card.append(el('div',j.derivative_status==='failed'?'副本轉檔失敗，可重試':'MP3 / 播放副本製作中…','processing-note'));if(j.error)card.append(el('div',j.error,'error'));if(j.derivative_error)card.append(el('div',j.derivative_error,'error'));const a=el('div',undefined,'actions');a.append(button('查看 Log',()=>{logJob=String(j.id);$('log-job').value=logJob;show('logs')},''));if(j.status==='failed')a.append(button('重試下載',async()=>{await api(`/api/jobs/${j.id}/retry`,{});await refresh()},''));if(j.status==='done'&&j.derivative_status==='failed')a.append(button('重試轉檔',async()=>{await api(`/api/jobs/${j.id}/process`,{});await refresh()},''));const origin=el('a','原始連結');origin.href=j.url;origin.target='_blank';origin.rel='noopener noreferrer';origin.className='job-meta';a.append(origin);card.append(a);target.append(card)}$('paging').hidden=false;$('prev').disabled=offset===0;$('next').disabled=jobs.length<100;$('page-number').textContent=`第 ${offset/100+1} 頁`;}
function play(j){if(j.status!=='done'){notice(j.status==='recording'?'正在邊播邊錄製，直播結束並完成合併後可在這裡播放。':'這份收藏還在下載，完成後就能播放。');return}$('player-title').textContent=j.title;$('player-media').replaceChildren();$('player-downloads').replaceChildren();downloadLinks(j.files,$('player-downloads'));const playable=j.files.filter(f=>f.role==='preview'||f.role==='mp3');const picker=$('playback-picker');picker.replaceChildren();for(const f of playable){const option=el('option',(f.role==='preview'?'影片 · ':'MP3 · ')+f.path.split('/').pop());option.value=String(f.id);picker.append(option)}$('playback-picker-label').hidden=playable.length<2;function load(){const f=playable.find(f=>String(f.id)===picker.value)||playable[0];if(!f){$('player-note').textContent=j.derivative_status==='failed'?'播放副本轉檔失敗；可先下載最高畫質原檔，或重試轉檔。':'播放副本還在製作中；最高畫質原檔已可下載。';return}const media=el(f.role==='mp3'?'audio':'video');media.controls=true;media.preload='metadata';media.setAttribute('playsinline','');media.src='/stream/'+f.id;media.onerror=()=>{$('player-note').textContent='播放失敗，請查看 Log 或下載原檔。'};$('player-media').replaceChildren(media);$('player-note').textContent=f.role==='preview'?'正在播放瀏覽器相容副本；最高畫質原檔仍完整保存。':'正在播放 MP3 聲音副本。';media.play().catch(()=>{})}picker.onchange=load;if(!$('player-dialog').open)$('player-dialog').showModal();load()}
function stopPlayer(){$('player-media').querySelectorAll('video,audio').forEach(m=>{m.pause();m.removeAttribute('src');m.load()});$('player-media').replaceChildren()}
$('close-player').onclick=()=>{$('player-dialog').close();stopPlayer()};$('player-dialog').addEventListener('close',stopPlayer);$('player-dialog').addEventListener('click',e=>{if(e.target===$('player-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
async function refresh(){if(busy||page==='settings')return;busy=true;const current=page;try{if(current==='channels'){channels=await api('/api/channels');if(page===current)renderChannels(channels);$('paging').hidden=true}else if(current==='logs'){const logs=await api('/api/logs'+(logJob?'?job='+encodeURIComponent(logJob):''));if(page!==current)return;const box=$('log-content'),nearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<80;box.textContent=logs.map(l=>`${new Date(l.ts*1000).toLocaleString()} [${l.level}]${l.job?' #'+l.job:''} ${l.message}`).join('\n');if(nearBottom)box.scrollTop=box.scrollHeight;$('paging').hidden=true}else {let query='?offset='+offset,target;if(current==='detail'){await reloadChannel();query+=`&channel=${channel}&kind=${kind}`;if(downloadedOnly)query+='&status=done';target=$('detail-jobs');$('videos-tab').classList.toggle('selected',kind==='video');$('live-tab').classList.toggle('selected',kind==='live');$('all-filter').classList.toggle('selected',!downloadedOnly);$('downloaded-filter').classList.toggle('selected',downloadedOnly)}else if(current==='single'){if(!channels.length)channels=await api('/api/channels');populateTargets(channels);query+='&single=1';target=$('single-jobs')}else target=$('all-jobs');const jobs=await api('/api/jobs'+query);if(page===current)renderJobs(jobs,target)}}finally{busy=false;if(page!==current)refresh().catch(notice)}}
async function status(){try{const s=await api('/api/status');$('runtime').textContent=`yt-dlp ${s.version} · 直播檢查 ${s.live_poll_seconds}s · `+s.queues.map(q=>`${labels[q.status]} ${q.count}`).join(' / ')}catch(e){notice(e)}}

function providerName(platform){return {youtube:'YouTube',twitch:'Twitch',twitter:'Twitter / X'}[platform]||platform}
function populateTargets(list){const current=$('download-target').value;$('download-target').replaceChildren(el('option','獨立下載'));$('download-target').firstChild.value='';for(const c of list){const o=el('option',c.name);o.value=String(c.id);$('download-target').append(o)}$('download-target').value=current}
async function reloadChannel(){channels=await api('/api/channels');const c=channels.find(c=>c.id===channel);if(c){renderHero(c);renderSources(c)}return c}
function renderSources(c){const list=$('source-list');list.replaceChildren();for(const source of c.sources||[]){const row=el('div',undefined,'source-row');row.append(el('span',providerName(source.platform),'badge'));const url=el('a',source.url,'source-url');url.href=source.url;url.target='_blank';url.rel='noopener noreferrer';row.append(url,button(source.enabled?'暫停來源':'恢復來源',async()=>{await api(`/api/sources/${source.id}/toggle`,{});await reloadChannel()},'ghost'));if(source.error)row.append(el('div',source.error,'error'));list.append(row)}}
$('rename-channel').onsubmit=async e=>{e.preventDefault();try{await api(`/api/channels/${channel}/name`,{name:$('channel-name').value});await reloadChannel();notice('訂閱名稱已保存')}catch(e){notice(e)}};
$('add-source').onsubmit=async e=>{e.preventDefault();try{await api(`/api/channels/${channel}/sources`,{url:$('source-url').value});$('source-url').value='';await reloadChannel();notice('新來源已加入同一份影音庫 ♡')}catch(e){notice(e)}};
async function openImages(){imageRole='avatar';await renderImages();if(!$('images-dialog').open)$('images-dialog').showModal()}
async function renderImages(){const images=await api(`/api/channels/${channel}/images`);const c=channels.find(c=>c.id===channel);const list=$('image-history');list.replaceChildren();$('avatar-history-tab').classList.toggle('selected',imageRole==='avatar');$('banner-history-tab').classList.toggle('selected',imageRole==='banner');const filtered=images.filter(x=>x.role===imageRole);if(!filtered.length)list.append(el('p','還沒有保存的圖片，先按「重新取得 YouTube 圖片」。','empty'));for(const item of filtered){const active=c&&c['active_'+imageRole]===item.id;const b=button('',async()=>{await api(`/api/channels/${channel}/images/select`,{id:item.id});await reloadChannel();await renderImages();$('image-notice').textContent='已換上你選的圖片 ♡'},'history-card '+(imageRole==='avatar'?'avatar-history ':'')+(active?'selected':''));b.setAttribute('aria-pressed',String(active));b.append(image('/asset/image/'+item.id,imageRole+' 第 '+item.id+' 版'),el('div',(active?'✓ 使用中 · ':'')+new Date(item.created*1000).toLocaleString()));list.append(b)}}
$('avatar-history-tab').onclick=()=>{imageRole='avatar';renderImages().catch(notice)};
$('banner-history-tab').onclick=()=>{imageRole='banner';renderImages().catch(notice)};
$('close-images').onclick=()=>$('images-dialog').close();
const runtimeFields={
LIVE_POLL_SECONDS:['直播檢查週期（秒）',30,10,3600],LIVE_SCAN_LIMIT:['YouTube 最新直播檢查數',10,1,200],
TWITTER_POLL_SECONDS:['X 新貼文檢查週期（秒）',300,60,86400],SCAN_SECONDS:['全量歷史掃描週期（秒）',21600,60,604800],
UPDATE_SECONDS:['yt-dlp 更新週期（秒）',86400,300,604800],DOWNLOAD_WORKERS:['一般下載工作數',2,1,16],
LIVE_WORKERS:['直播錄製工作數',4,1,16],TRANSCODE_WORKERS:['轉檔工作數',1,1,8],TRANSCODE_THREADS:['每次轉檔執行緒數',2,1,32],
PLAYBACK_HEIGHT:['播放副本最大高度',1080,144,4320]};
function renderRuntimeSettings(){prefs.runtime=prefs.runtime||{};const target=$('runtime-settings');target.replaceChildren();for(const [key,[label,defaultValue,min,max]] of Object.entries(runtimeFields)){const l=el('label',undefined,'runtime-field');const input=el('input');input.type='number';input.min=String(min);input.max=String(max);input.value=String(prefs.runtime[key]??defaultValue);input.oninput=()=>{prefs.runtime[key]=Number(input.value)};l.append(el('span',label),input,el('small',key));target.append(l)}const version=el('label',undefined,'runtime-field');const select=el('select');for(const v of ['stable','nightly']){const o=el('option',v);o.value=v;select.append(o)}select.value=prefs.runtime.YTDLP_CHANNEL||'stable';select.onchange=()=>{prefs.runtime.YTDLP_CHANNEL=select.value};version.append(el('span','yt-dlp 更新來源'),select,el('small','YTDLP_CHANNEL'));target.append(version);const live=el('label',undefined,'runtime-field checkbox-field');const checkbox=el('input');checkbox.type='checkbox';checkbox.checked=!!prefs.runtime.LIVE_FROM_START;checkbox.onchange=()=>{prefs.runtime.LIVE_FROM_START=checkbox.checked};live.append(checkbox,el('span','嘗試從直播起點錄製（DVR 實驗功能）'));target.append(live)}
$('save-runtime').onclick=async()=>{try{prefs=await api('/api/settings',prefs);applyPrefs();renderSettings();notice('執行設定已保存，新任務會套用；進行中的任務繼續完成。')}catch(e){notice(e)}};
async function secretAction(body){const result=await api('/api/secrets',body);prefs.cookies=result.cookies;prefs.x_api_configured=result.x_api_configured;renderCookieSettings();$('x-api-status').textContent=prefs.x_api_configured?'Token 已保存':'尚未設定 Token';notice('登入資料設定已更新；已保存的秘密值不會回傳。')}
function renderCookieSettings(){const target=$('cookie-settings');target.replaceChildren();for(const platform of ['youtube','twitch','twitter']){const state=(prefs.cookies||{})[platform]||{};const card=el('div',undefined,'cookie-card');const head=el('div',undefined,'cookie-head');head.append(el('h3',providerName(platform)),el('span',state.configured?'專用 cookies 已保存':state.legacy_available?'使用舊 cookies.txt':'尚未設定','pill'));const enabled=el('label'),check=el('input');check.type='checkbox';check.checked=state.enabled!==false;check.onchange=async()=>{const requested=check.checked;try{await secretAction({platform,enabled:requested})}catch(e){check.checked=!requested;notice(e)}};enabled.append(check,el('span','啟用 cookies'));head.append(enabled);card.append(head);const upload=el('label',undefined,'cookie-upload');upload.append(el('span','上傳 cookies.txt'));const file=el('input');file.type='file';file.accept='.txt,text/plain';file.onchange=async()=>{try{const selected=file.files[0];if(!selected)return;if(selected.size>2*1024*1024)throw Error('檔案不能超過 2 MB');await secretAction({platform,content:await selected.text()})}catch(e){notice(e)}};upload.append(file);card.append(upload);const details=el('details');const summary=el('summary','或貼上 cookies 內容');const textarea=el('textarea');textarea.placeholder='# Netscape HTTP Cookie File';textarea.setAttribute('aria-label',providerName(platform)+' cookies 內容');textarea.autocomplete='off';details.append(summary,textarea);const actions=el('div',undefined,'settings-actions');actions.append(button('保存貼上的 cookies',async()=>{await secretAction({platform,content:textarea.value});textarea.value=''}),button('移除專用 cookies',async()=>{await secretAction({platform,delete:true})},'ghost'));details.append(actions);card.append(details,el('p','移除專用檔案後，若仍有 cookies/cookies.txt 會退回使用它；停用 cookies 可完全停止此平台使用登入資料。','cookie-warning'));target.append(card)}}
$('save-x-api').onclick=async()=>{try{await secretAction({platform:'x-api',content:$('x-api-token').value});$('x-api-token').value=''}catch(e){notice(e)}};
$('delete-x-api').onclick=()=>secretAction({platform:'x-api',delete:true}).catch(notice);

api('/api/settings').then(s=>{prefs=s;applyPrefs();if(page==='settings')renderSettings()}).catch(notice);refresh().catch(notice);status();setInterval(()=>refresh().catch(notice),5000);setInterval(status,30000);
