const $=id=>document.getElementById(id);let page='channels',channel=null,kind='video',offset=0,logJob='',busy=false;
const labels={queued:'等待下載 / 重試',downloading:'下載中',recording:'直播錄製中',done:'完成',failed:'失敗'};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function button(text,fn,cls='ghost'){const n=el('button',text,cls);n.onclick=()=>Promise.resolve(fn()).catch(notice);return n;}
function notice(e){$('notice').textContent=e.message||String(e);}
async function api(path,body){const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error||r.statusText);return j;}
function show(p){page=p;offset=0;for(const id of ['channels','single','all','detail','logs'])$(id).hidden=id!==p;document.querySelectorAll('nav button').forEach(n=>n.classList.toggle('selected',n.dataset.page===p));$('paging').hidden=true;refresh().catch(notice);}
document.querySelectorAll('nav button').forEach(n=>n.onclick=()=>show(n.dataset.page));
$('back').onclick=()=>show('channels');
$('videos-tab').onclick=()=>{kind='video';offset=0;refresh().catch(notice)};
$('live-tab').onclick=()=>{kind='live';offset=0;refresh().catch(notice)};
$('subscribe').onsubmit=async e=>{e.preventDefault();try{await api('/api/channels',{url:$('channel-url').value});$('channel-url').value='';notice('已新增訂閱，開始掃描歷史影片並監控直播。');await refresh()}catch(e){notice(e)}};
$('download').onsubmit=async e=>{e.preventDefault();try{const j=await api('/api/download',{url:$('link-url').value});$('link-url').value='';notice(`任務 #${j.id} 已加入佇列`);await refresh()}catch(e){notice(e)}};
$('update').onclick=async()=>{try{await api('/api/update',{});notice('已啟動更新檢查，結果請看 Log。')}catch(e){notice(e)}};
$('apply-log').onclick=()=>{logJob=$('log-job').value;refresh().catch(notice)};
$('prev').onclick=()=>{offset=Math.max(0,offset-100);refresh().catch(notice)};
$('next').onclick=()=>{offset+=100;refresh().catch(notice)};
function date(t){return t?new Date(t*1000).toLocaleString():'尚未檢查'}
function renderJobs(jobs,target){target.replaceChildren();if(!jobs.length)target.append(el('p','目前沒有任務或下載項目。','muted'));for(const j of jobs){const row=el('div',undefined,'job'),main=el('div',undefined,'job-main');main.append(el('div',j.title,'job-title'),el('div',`#${j.id} · ${j.kind==='live'?'直播':'影片'} · ${date(j.created)} · 嘗試 ${j.attempts} 次`,'job-meta'));const a=el('a','原始連結');a.href=j.url;a.target='_blank';a.rel='noopener noreferrer';main.append(a);if(j.error)main.append(el('div',j.error,'error'));const files=el('div',undefined,'files');for(const f of j.files){const a=el('a','↓ '+f.path.split('/').pop());a.href='/file/'+f.id;files.append(a)}main.append(files);const actions=el('div',undefined,'actions');actions.append(button('查看 Log',()=>{logJob=String(j.id);$('log-job').value=logJob;show('logs')}));if(j.status==='failed')actions.append(button('重試',async()=>{await api(`/api/jobs/${j.id}/retry`,{});await refresh()}));main.append(actions);row.append(main,el('span',labels[j.status]||j.status,'badge '+j.status));target.append(row)}$('paging').hidden=false;$('prev').disabled=offset===0;$('next').disabled=jobs.length<100;$('page-number').textContent=`第 ${offset/100+1} 頁`;}
async function refresh(){if(busy)return;busy=true;try{
if(page==='channels'){const list=await api('/api/channels');$('channel-list').replaceChildren();if(!list.length)$('channel-list').append(el('p','新增第一個頻道，即可開始建立影音庫。','muted'));for(const c of list){const card=el('article',undefined,'card');card.append(button(c.name,()=>{channel=c.id;kind='video';$('detail-title').textContent=c.name;show('detail')},'channel-title'),el('p',c.url,'url'),el('div',`${c.enabled?'追蹤中':'已暫停'} · 已完成 ${c.downloaded} · 錄製中 ${c.recording}`,'muted'),el('div',`歷史掃描：${date(c.last_scan)}`,'job-meta'),el('div',`直播檢查：${date(c.last_live)}`,'job-meta'));if(c.error)card.append(el('div',c.error,'error'));const a=el('div',undefined,'actions');a.append(button('立即掃描',async()=>{await api(`/api/channels/${c.id}/scan`,{});notice('已安排重新掃描')}),button(c.enabled?'暫停追蹤':'恢復追蹤',async()=>{await api(`/api/channels/${c.id}/toggle`,{});busy=false;await refresh()}));card.append(a);$('channel-list').append(card)}$('paging').hidden=true}
else if(page==='logs'){const logs=await api('/api/logs'+(logJob?'?job='+encodeURIComponent(logJob):''));const box=$('log-content');const nearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<80;box.textContent=logs.map(l=>`${date(l.ts)} [${l.level}]${l.job?' #'+l.job:''} ${l.message}`).join('\n');if(nearBottom)box.scrollTop=box.scrollHeight;$('paging').hidden=true}
else {let query='?offset='+offset,target;if(page==='detail'){query+=`&channel=${channel}&kind=${kind}`;target=$('detail-jobs');$('videos-tab').classList.toggle('selected',kind==='video');$('live-tab').classList.toggle('selected',kind==='live')}else if(page==='single'){query+='&single=1';target=$('single-jobs')}else target=$('all-jobs');renderJobs(await api('/api/jobs'+query),target)}
}finally{busy=false}}
async function status(){try{const s=await api('/api/status');$('runtime').textContent=`yt-dlp ${s.version} · 直播檢查 ${s.live_poll_seconds}s | `+s.queues.map(q=>`${labels[q.status]} ${q.count}`).join(' / ')}catch(e){notice(e)}}
refresh().catch(notice);status();setInterval(()=>refresh().catch(notice),5000);setInterval(status,30000);
